{{- if .Values.clusterrole.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nydus-snapshotter.clusterRoleName" . }}
  labels:
    {{- include "nydus-snapshotter.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
{{- end }}